backend:
  name: git-gateway
  branch: main 

media_folder: 'public/img'
public_folder: '/img'

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "image", label: "Image", widget: "image"}
      - {name: "description", label: "Description", widget: "text"}
